name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poetry-version: ["1.8.5", "2.0.0", "latest"]
    
    name: Poetry ${{ matrix.poetry-version }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Fish and Poetry
      run: |
        sudo apt-add-repository ppa:fish-shell/release-3
        sudo apt update
        sudo apt install -y fish python3-pip
        if [ "${{ matrix.poetry-version }}" == "latest" ]; then
          pip install poetry
        else
          pip install "poetry==${{ matrix.poetry-version }}"
        fi
        # Print poetry version for debugging
        poetry --version
        
    - name: Run tests
      run: make test-verbose
      
    - name: Run lint
      run: make lint